### ISSUE TITLE
RDChecksum: FileChecksumFile - Change of output order

### ISSUE THREAD

**Issue by heikoh81** [rdiez/Tools#6]
Hi,

I use rdchecksum on very large file collections.
If I delete or move files, this produces the message "No such file or directory"

However, as file and folder names are of different length, the verification file is very hard to scroll through, as the position of the error message jumps back and forth.
`Very long Testfolder/Even Longer Folder Name\Very Long Filename.txt	No such file or directory
Testfolder/Testfolder/Testfile1.txt	No such file or directory
`

It would be faster if the error message is the first column, followed by folder and file name.
Thus, i could easily scroll through the verification file to see if there is bitrod or just a moved or deleted file.
```
No such file or directory          Very long Testfolder/Even Longer Folder Name\Very Long Filename.txt
No such file or directory          Testfolder/Testfolder/Testfile1.txt
```

Thanks,
Heiko

**Comment by rdiez** [comment]
I do not think that reordering the columns is a good idea. Other users would then complain that they would rather see the filenames first, in order to visually delimit the affected subdirectories.

The following shell commands align and reorder the columns for convenience when manually inspecting the report files:

```
column  --table  --separator $'\t'                     FileChecksums.txt.verification.report
column  --table  --separator $'\t'  --table-order 2,1  FileChecksums.txt.verification.report
```

**Comment by heikoh81** [comment]
Thanks, these commands work for me, I added 
`column  --table  --separator $'\t'  --table-order 2,1  FileChecksums.txt.verification.report > Verification.Report.txt `
to write the output to a file.

However, German special characters like ä,ü,ö are scrambled. Not that big a problem, though.
Probably because I didn't bother to install german locales on my raspberry, didn't need them so far...

Output of locale:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by rdiez** [comment]
When redirecting to a file, you may need to set the width like this:
`--output-width 999999`
Otherwise, oversized column fields may end up on the next line.

I am running Ubuntu MATE 22.04 on a German laptop and I don't see any problems with German characters. The report file starts with the UTF-8 BOM and the file that 'column' generates has the UTF-8 BOM too, so there should not be any problems. Maybe your Raspberry Pi does not have all UTF-8 / internationalisation support installed, but I am no expert in that area. What version of 'column' do you have?

**Comment by heikoh81** [comment]
No change with parameter --output-width.
locale german-UTF8 is selected with raspi-config, but not displayed in bash (see output of locale above).

column --version
`column from util-linux 2.36.1`

I noticed the following:
When the result of column is printed to bash, special characters are ok.
So the problem seems to occur when printing to file > Verification.Report.txt

Don't know how that can be solved.
It is not that big a problem for me, though, as I just need to quickly see if there are real bitrod-errors or just moved or deleted files.
And the column-command (that I didn't know before) does exactly that.

Thanks.

**Comment by rdiez** [comment]
I am using "column from util-linux 2.37.2", but that minor version difference shouldn't matter.

I do not know what may be causing that kind of trouble. I am not seeing it on my system. How do you look at the file? It may be the text editor you are using. What happens if you do "cat Verification.Report.txt" on the same terminal?

What does this command say?

`file Verification.Report.txt`

It should say:

`Verification.Report.txt: Unicode text, UTF-8 (with BOM) text`

**Comment by heikoh81** [comment]
It was indeed the setting in my text editor.
After changing encoding to UTF everything is fine even in the output file of column.

Thanks for the big and fast help!
